---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: babylon-events-console
  name: babylon-events-console

parameters:
- name: GIT_REPO
  value: https://github.com/redhat-gpte-devopsautomation/babylon-events-console.git
- name: NAME
  value: babylon-events-console

objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${NAME}
  spec:
    output:
      to:
        kind: ImageStreamTag
        name: ${NAME}:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      git:
        uri: ${GIT_REPO}
        ref: master
    strategy:
      type: Docker
      dockerStrategy:
        from:
          kind: DockerImage
          name: registry.access.redhat.com/ubi8/python-36:latest
    triggers: []
