apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: babylon events console
  name: babylon-events-console

parameters:
- name: NAME
  displayName: Name to apply to template resources
  value: babylon-events-console
  required: true
- name: ACCESS_PASSWORD
  displayName: User Access Password
  description: >-
    Optional user access password
  generate: expression
- name: ADMIN_PASSWORD
  displayName: Administrative Password
  generate: expression
  from: '[a-zA-Z0-9]{16}'
  required: true
- name: TEMPLATE
  displayName: Template
  description: >-
    Template to provision for users.
    Template may be given as the template name or "<namespace>//<name>".
  required: true
- name: TEMPLATE_PARAMETERS
  displayName: Template parameters
  description: >-
    Parameters to pass to template when creating user lab environments.
    Provide parameters as a JSON or YAML dictionary.
  value: '{}'
  required: true
- name: DATABASE_SERVICE_NAME
  displayName: Redis database service name
  description: >-
    Redis database service name for session data.
    Redis must be deployed in same namespace as the events console.
  value: babylon-events-console-redis
  required: true
- name: HOSTNAME
  displayName: Route Hostname
  description: >-
    Hostname for events console route.
  required: false
- name: IMAGE
  displayName: Babylon events console image
  value: quay.io/redhat-cop/babylon-events-console:latest
  required: true
- name: POOLBOY_DOMAIN
  displayName: Poolboy operator CRD domain
  value: poolboy.gpte.redhat.com
  required: true

objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: ${NAME}

- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: ${NAME}
  rules:
  - apiGroups:
    - template.openshift.io
    resources:
    - templates
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ${POOLBOY_DOMAIN}
    resources:
    - resourceclaims
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - watch
    - update

- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: ${NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: ${NAME}
  subjects:
  - kind: ServiceAccount
    name: ${NAME}

- apiVersion: v1
  kind: Secret
  metadata:
    name: ${NAME}
  stringData:
    access_password: ${ACCESS_PASSWORD}
    admin_password: ${ADMIN_PASSWORD}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${NAME}
  spec:
    selector:
      matchLabels:
        app: ${NAME}
    replicas: 1
    template:
      metadata:
        labels:
          app: ${NAME}
      spec:
        serviceAccountName: ${NAME}
        containers:
        - name: babylon-events-console
          env:
          - name: ACCESS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}
                key: access_password
          - name: ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${NAME}
                key: admin_password
          - name: POOLBOY_DOMAIN
            value: ${POOLBOY_DOMAIN}
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${DATABASE_SERVICE_NAME}
                key: database-password
          - name: REDIS_SERVER
            value: ${DATABASE_SERVICE_NAME}:6379
          - name: TEMPLATE
            value: ${TEMPLATE}
          - name: TEMPLATE_PARAMETERS
            value: ${TEMPLATE_PARAMETERS}
          image: ${IMAGE}
          ports:
          - containerPort: 8080

- apiVersion: v1
  kind: Service
  metadata:
    name: ${NAME}
  spec:
    ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${NAME}
    type: ClusterIP

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${NAME}
  spec:
    host: ${HOSTNAME}
    port:
      targetPort: 8080
    to:
      kind: Service
      name: ${NAME}
